version: "3.3"

services:
    
   # wordpress:
   #     build: requirements/wordpress/.
   #    volumes:
   #        - /home/user42/data/front.:/usr/var/html
   #    restart: always
   #    container_name: wordpress

    mariadb:
        build: requirements/mariadb/.
        restart: always
        env_file:
            - .env
        container_name: mariadb

    nginx:
        build: requirements/nginx/.
        volumes:
            - /home/user42/data/front/.:/usr/var/www/html
        ports:
            - 80:80
        container_name: nginx
