version: "3.3"

services:
    
    wordpress:
        depends_on:
            - mariadb
        build: requirements/wordpress/.
        image: wordpress
        volumes:
            - /home/user42/data/front/.:/var/www/html/
        restart: always
        expose:
            - 9000
        env_file:
            - .env
        networks:
            - inception
        container_name: wordpress

    mariadb:
        build: requirements/mariadb/.
        image: mariadb
        volumes:
            - /home/user42/data/db/.:/var/lib/mysql
        expose:
            - 3306
        restart: always
        env_file:
            - .env
        networks:
            - inception
        container_name: mariadb

    nginx:
        build: requirements/nginx/.
        image: nginx
        volumes:
            - /home/user42/data/front/.:/usr/var/www/html
        ports:
            - 443:443
        networks:
            - inception
        container_name: nginx

networks:
    inception:
        driver: bridge
