version: "3.3"

services:
    serv_nginx:
        build: requirements/nginx/.
        volumes:
            - /home/user42/data/front/.:/usr/share/nginx/html
        ports:
            - 80:80
        container_name: nginx
