version: "3.3"

services:
    
   # wordpress:
   #     build: requirements/wordpress/.
   #    volumes:
   #        - /home/user42/data/front.:/usr/var/html
   #    restart: always
   #    container_name: wordpress

    mariadb:
        build: requirements/mariadb/.
        volumes:
            - /home/user42/data/db/.:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${USER_NAME}
            MYSQL_PASSWORD: ${USER_PASS}
        restart: always
        container_name: mariadb

    nginx:
        build: requirements/nginx/.
        volumes:
            - /home/user42/data/front/.:/usr/var/www/html
        ports:
            - 80:80
        container_name: nginx
