version: "3.3"

services:
    
    wordpress:
        depends_on:
            - mariadb
        build: requirements/wordpress/.
        image: wordpress:v1.0
        volumes:
            - /home/acastelb/data/front:/var/www/html/
        restart: always
        expose:
            - 9000
        env_file:
            - .env
        networks:
            - inception
        container_name: wordpress

    mariadb:
        build: requirements/mariadb/.
        image: mariadb:v1.0
        volumes:
            - /home/acastelb/data/db/.:/var/lib/mysql
        expose:
            - 3306
        restart: always
        env_file:
            - .env
        networks:
            - inception
        container_name: mariadb

    nginx:
        build: requirements/nginx/.
        depends_on:
            - wordpress
        image: nginx:v1.0
        volumes:
            - /home/acastelb/data/front:/var/www/html
        ports:
            - 443:443
        restart: always
        networks:
            - inception
        container_name: nginx

networks:
    inception:
        driver: bridge
