version: "3.3"

services:
    
    wordpress:
        depends_on:
            - mariadb
        build: requirements/wordpress/.
        image: wordpress:v1.0
        volumes:
            - shared_front:/var/www/html/
        restart: always
        expose:
            - 9000
        env_file:
            - .env
        networks:
            - inception
        container_name: wordpress

    mariadb:
        build: requirements/mariadb/.
        image: mariadb:v1.0
        volumes:
            - /home/user42/data/db/.:/var/lib/mysql
        expose:
            - 3306
        restart: always
        env_file:
            - .env
        networks:
            - inception
        container_name: mariadb

    nginx:
        build: requirements/nginx/.
        depends_on:
            - wordpress
        image: nginx:v1.0
        volumes:
            - shared_front:/var/www/html
        ports:
            - 443:443
        networks:
            - inception
        container_name: nginx

volumes:
    shared_front:
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: '/home/user42/data/front'
networks:
    inception:
        driver: bridge
