version: "3.3"

services:
    nginx:
        build: requirements/nginx/.
        volumes:
            - /home/user42/data/front/.:/usr/var/www/html
        ports:
            - 80:80
        container_name: nginx
