version: "3.3"

services:
    
    wordpress:
        build: requirements/wordpress/.
        # volumes:
        #    - /home/user42/data/front/.:/var/www/html/
        restart: always
        expose:
            - 9000
        env_file:
            - .env
        container_name: wordpress

    # mariadb:
    #    build: requirements/mariadb/.
    #    volumes:
    #        - /home/user42/Documents/42/inception/srcs/requirements/mariadb/conf/.:/etc/mysql/conf.d/.
    #        - /home/user42/data/db/.:/var/lib/mysql
    #    expose:
    #        - 3306
    #    restart: always
    #    env_file:
    #        - .env
    #    container_name: mariadb

    nginx:
        build: requirements/nginx/.
        volumes:
            - /home/user42/data/front/.:/usr/var/www/html
        ports:
            - 80:80
        container_name: nginx
